services:
  client:
    build: ./client
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CLIENT_URL=http://localhost:3000
      - SERVER_URL=http://localhost:3001
      - CLIENT_ID=oauth-client
      - CLIENT_SECRET=057307322c9e3b1db7d3aa976b8af405
  server:
    build: ./server
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - ADMIN_PASSWORD=admin
      - CLIENT_SECRET=057307322c9e3b1db7d3aa976b8af405
      - CLIENT_URL=http://localhost:3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    restart: always
  nginx-client:
    build: ./nginx-client
    ports:
      - 3000:80
    depends_on:
      - client
    restart: always
  nginx-server:
    build: ./nginx-server
    ports:
      - 3001:80
    depends_on:
      - server
    restart: always
  crawler:
    build: ./crawler
    restart: always
    environment:
      - CLIENT_URL=http://client:3000
      - SERVER_URL=http://server:3001
      - USERNAME=admin
      - PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  redis: