services:
  webapp:
    build: ./app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ADMIN_PASSWORD=admin
  nginx:
    build: ./nginx
    ports:
      - 22355:80
    depends_on:
      - webapp
    restart: always
  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    ports:
      - 16379:6379
    restart: always
  crawler:
    build: ./crawler
    restart: always
    environment:
      - APP_URL=http://webapp:22355/
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  redis:
